# tasks file
---
- name: cli | wait for server to come online
  command: >
    curl -sSLD - {{ jenkins_url }}/cli/
  args:
    warn: false
  register: _jenkins_online
  until: >
    (_jenkins_online.stdout.find("403 Forbidden") != -1)
    or (_jenkins_online.stdout.find("200 OK") != -1)
    and (_jenkins_online.stdout.find("Please wait while") == -1)
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  changed_when: false
  tags:
    - jenkins-cli-online

- name: cli | create directory
  file:
    path: "{{ jenkins_cli_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - jenkins-cli-directory

- name: cli | download (latest)
  get_url:
    url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_cli_path }}"
    owner: root
    group: root
    mode: 0644
  register: _jenkins_cli_download
  until: "'OK' in _jenkins_cli_download.msg or 'file already exists' in _jenkins_cli_download.msg"
  retries: 10
  delay: 10
  tags:
    - jenkins-cli-download
