# tasks file
---
- name: install | dependencies
  apt:
    name: "{{ jenkins_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - jenkins-install-dependencies

- name: install | additional
  apt:
    name: "{{ jenkins_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - jenkins-install-additional

- block:

    # See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
    - name: ensure man directory
      file:
        path: /usr/share/man/man1
        state: directory
        recurse: true
      when:
        - ansible_distribution_major_version is version('18', '>=')

    - name: install | dependencies (java)
      apt:
        name: "{{ jenkins_java_dependencies }}"
        state: "{{ apt_install_state | default('latest') }}"

  when: not jenkins_assume_java_provided | bool
  tags:
    - jenkins-install-dependencies
    - jenkins-install-dependencies-java

- name: install | jenkins
  apt:
    name: jenkins
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - jenkins-install-jenkins
