- name: Launching aws ec2 instance
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Launching ec2 instance with ec2 module
    ec2-instance:
     name: testing
     instance_type: t2.micro
     image_id: ami-0fb653ca2d3203ac1
     region: us-east-2
